version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD:
      MYSQL_USER:
      
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data:
